### ISSUE TITLE
"db.Engine.Close() used as value"

### ISSUE THREAD

**Issue by houzefa-abba** [orus-io/yago#9]
Hey,

When updating to the latest version, I get the message in the title:

```
habba@zouzou-asus-laptop:~$ go get -u github.com/orus-io/yago
# github.com/orus-io/yago
Dev/go/src/github.com/orus-io/yago/db.go:93: db.Engine.Close() used as value
```

Seems to come from rev c904eaa803ecb17a1be942562f8fcf897d404f03.

**Comment by cdevienne** [comment]
Try updating qb too

**Comment by houzefa-abba** [comment]
Thanks for the pointer - had some update woes; all good now.
